language: node_js
node_js:
  - "0.12"
install:
  - "npm install -g protractor cucumber phantomjs lr-http-server"
  - "webdriver-manager update --standalone"
  - "npm install"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 5" # give xvfb some time to start
  - "npm run start 2>&1 &" # start a Web server
  - java -jar ./node_modules/protractor/selenium/selenium-server-standalone-2.45.0.jar -Dwebdriver.chrome.driver=./selenium/chromedriver &
  - "sleep 5" # give Web server some time to bind to sockets, etc
script:
  - "npm run cucumber"
